import 'package:app_bachhoa/models/supplier.dart';
import 'package:app_bachhoa/services/supplier_repository.dart';
import 'package:flutter/material.dart';

class NhaCungCapPage extends StatefulWidget { const NhaCungCapPage({super.key}); @override State<NhaCungCapPage> createState()=>_NhaCungCapPageState(); }
class _NhaCungCapPageState extends State<NhaCungCapPage>{
 final _repo=SupplierRepository(); List<Supplier> _items=[]; bool _loading=true;
 @override void initState(){super.initState();_load();}
 Future<void> _load() async{setState(()=>_loading=true); final data=await _repo.getAll(); if(!mounted)return; setState(() { _items = data; _loading = false; });}
 Future<void> _form({Supplier? supplier}) async{ final n=TextEditingController(text:supplier?.name??''); final p=TextEditingController(text:supplier?.phone??''); final a=TextEditingController(text:supplier?.address??''); final note=TextEditingController(text:supplier?.note??''); Supplier? saved; try{ final ok=await showDialog<bool>(context: context,builder:(ctx)=>AlertDialog(title:Text(supplier==null?'Thêm nhà cung cấp':'Sửa nhà cung cấp'),content:SingleChildScrollView(child:Column(mainAxisSize:MainAxisSize.min,children:[TextField(controller:n,decoration:const InputDecoration(labelText:'Tên nhà cung cấp')),const SizedBox(height:12),TextField(controller:p,decoration:const InputDecoration(labelText:'Số điện thoại')),const SizedBox(height:12),TextField(controller:a,decoration:const InputDecoration(labelText:'Địa chỉ')),const SizedBox(height:12),TextField(controller:note,decoration:const InputDecoration(labelText:'Ghi chú'))])),actions:[TextButton(onPressed:()=>Navigator.pop(ctx,false),child:const Text('Huỷ')),FilledButton(onPressed:(){if(n.text.trim().isEmpty)return; saved=Supplier(id:supplier?.id,name:n.text.trim(),phone:p.text.trim(),address:a.text.trim(),note:note.text.trim()); Navigator.pop(ctx,true);},child:const Text('Lưu'))])); if(ok==true&&saved!=null){await _repo.upsert(saved!); await _load();}}finally{n.dispose();p.dispose();a.dispose();note.dispose();}}
 Future<void> _delete(Supplier s) async{ if(s.id==null)return; await _repo.delete(s.id!); await _load();}
 @override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:const Text('Nhà cung cấp'),actions:[IconButton(onPressed:()=>_form(),icon:const Icon(Icons.add))]),body:_loading?const Center(child:CircularProgressIndicator()):RefreshIndicator(onRefresh:_load,child:_items.isEmpty?ListView(children:const[ SizedBox(height:220),Center(child:Text('Chưa có nhà cung cấp.'))]):ListView.separated(padding:const EdgeInsets.all(16),itemCount:_items.length,separatorBuilder: (_, separatorIndex) =>const SizedBox(height:8),itemBuilder:(c,i){final s=_items[i];return Card(child:ListTile(leading:const Icon(Icons.local_shipping_outlined),title:Text(s.name),subtitle:Text('${s.phone} • ${s.address}'),trailing:Row(mainAxisSize:MainAxisSize.min,children:[IconButton(onPressed:()=>_form(supplier:s),icon:const Icon(Icons.edit_outlined)),IconButton(onPressed:()=>_delete(s),icon:const Icon(Icons.delete_outline,color:Colors.red))])));})));
}

